### ISSUE TITLE
Can't query blocks on type post error

### ISSUE THREAD

**Issue by marcinsydor** [Quartz/wp-graphql-content-blocks#1]
I have installed and activated plugin and when I test a below query in GraphiQL then I'm getting an error message:
`Cannot query filed "blocks on type "post"`

```gql 
{
  page: postBy(uri: "hello-world") {
     title
     blocks {
	type
        innerHtml
    }
  }
}
```
Do I need to do anything else to make it work?

**Comment by chriszarate** [comment]
@marcinsydor Are you using the newest version of WPGraphQL? The filters moved a bit in `0.2.0` and I'm about to push up an update to address that.

**Comment by chriszarate** [comment]
Just pushed it up (on `master`)

**Comment by ilsx** [comment]
I have the same issue
`Cannot query field \"blocks\" on type \"RootQueryToPostConnection\`
I'm using the latest version of WPGraphQL.
Wich version is compatible with the latest wp-graphql-content-blocks ?
Thank you
