### ISSUE TITLE
core quote block is missing cite tag

### ISSUE THREAD

**Issue by dalecreativ** [Quartz/wp-graphql-content-blocks#10]
Hello,

Thanks for creating this plugin, it's been super useful for a current project.

I was looking for some help, or to make a request to handle the core/quote block `cite` tags.

When using the plugin the innerHtml of the quote block seems to remove the `cite` tag, but it keeps the inner text from the cite tag.  When disabling the plugin, or querying against post.content I see the `cite` tags are there, as expected.  When we switch the query to use blocks the `cite`  tags are removed from the innerHtml property again.

Is there anything that can be done to handle this so we can include the correct semantic markup for a blockquote block?

Any help or advice would be much appreciated.

**Comment by chriszarate** [comment]
Hi!

I think `cite` was just erroneously omitted from the list of HTML tags.

Quick fix: Add it to [this array](https://github.com/Quartz/wp-graphql-content-blocks/blob/master/src/types/shared/block-definitions.php#L145), e.g.:

```
'cite' => [
	'root_only' => false,
	'allow_root' => false,
],
```

**Comment by dalecreativ** [comment]
Thank you for your quick response @chriszarate.

Is it worth me dropping a PR in for the quick fix above?

**Comment by chriszarate** [comment]
@dalecreativ Definitely with thanks!

**Comment by dalecreativ** [comment]
Hi @chriszarate @Bhammy 

Should I have bumped a minor version along with the update made last week?
