### ISSUE TITLE
How is this project licensed?

### ISSUE THREAD

**Issue by nholik** [Quartz/wp-graphql-content-blocks#18]
Any chance a license file could be added to the project?  I'm not sure if this is open to fork and modify.

**Comment by chriszarate** [comment]
I no longer have access to this repo and can't give you advice about licensing / forking. I don't think this project is receiving updates. I can however point you to other emerging projects around blocks:

- https://github.com/Automattic/vip-decoupled-bundle
- https://github.com/wp-graphql/wp-graphql-block-editor

**Comment by nholik** [comment]
Thanks @chriszarate I'll check those projects out
