### ISSUE TITLE
Getting internal server error using this.

### ISSUE THREAD

**Issue by joshuaiz** [Quartz/wp-graphql-content-blocks#4]
In GraphiQL:

```javascript
query GET_POST($id: ID!) {
  post(id: $id) {
    blocks {
      attributes {
        name
        value
      }
      innerHtml
      tagName
      type
    }
  }
}
```

(with valid id)

returns:

```javascript
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "post",
        "blocks"
      ]
    }
  ],
  "data": {
    "post": {
      "blocks": null
    }
  }
}
```

It's not liking something in my install.

The site is loading and I'm able to get other GraphQL responses from the site so this is isolated to the plugin.

**Comment by BartoszLobejko** [comment]
Yeah, I'm having exactly the same issue.

**Comment by joshuaiz** [comment]
Bumping this. Would really like to use this plugin as I have a good use case for it but right now it doesn't work :(

**Comment by BartoszLobejko** [comment]
If you work with React.js you can use this component:
https://github.com/remarkablemark/html-react-parser
It does the same job and gives you a good control.

**Comment by joshuaiz** [comment]
@BartoszLobejko I use that to parse HTML in React for every project since I hate using `dangerouslySetInnerHTML` :) Yet in my case I'm trying to separate out code blocks from existing posts with a headless WP set up to add syntax highlighting. HTML-react-parser doesn't work for that. 

Content blocks theoretically could work so I could then add the syntax highlighting.

The problem is WPGraphQL returns the `content` as a string so there is no way to apply syntax highlighting to just a section. Which is were this content blocks plugin could work.

**Comment by BartoszLobejko** [comment]
@joshuaiz 
If I understand you well, you're talking about syntax highlighting on the client side when you display example code block on a post? 

Cant, you even achieve this with more complex rules for parsing content something like bellow? (different case but similar idea. )

`const options = {
    replace: domNode => {
      if (
        domNode.type === 'tag' &&
        domNode.name === 'div' &&
        domNode.attribs.class.includes('wp-caption')
      ) {
        if (
          domNode.children[0].name === 'img' &&
          domNode.children[1].name === 'p' &&
          domNode.children[1].attribs.class.includes('wp-caption-text')
        ) {
          return (
            <BetterImage
              data={mapImage(
                domNode.children[0],
                domToReact(domNode.children[1].children),
              )}
            />
          );
        }
      }
}
}
`

But Maybe I just get your problem the wrong way...

**Comment by joshuaiz** [comment]
@BartoszLobejko hmmm interesting idea although that kind of is an un-React way to do it. Plus I have some really long posts with lots of code blocks so that kind of thing would be a bit of a nightmare although I'm willing to give it a shot.

Obviously being able to parse out the `<pre><code>` blocks automagically would be a bit cleaner.

**Comment by BartoszLobejko** [comment]
@joshuaiz 
Yeah, I know is not ideal and I would prefer that wp-graphql-content-block would just work properly but if you can't have what you want you just do what you can ;) 

Why do you think is un-react way? You map HTML tags to react component, and then you have full control. The only and main difference is that is happening on the client side, not on the server side, and I guess you process something that is already processed on the server...

**Comment by joshuaiz** [comment]
@BartoszLobejko it's only un-React because I've been taught not to touch the DOM but sometimes you gotta do what you gotta do 👾

**Comment by CHEWX** [comment]
I'm getting this issue too. Any update?

The whole point of this plugin is to get a return in nodes, and not to use html parsing.

**Comment by ChristofferNE** [comment]
Bump

**Comment by magicspon** [comment]
Any updates on this?

**Comment by JacksonMalloy** [comment]
Looking for an update on this

**Comment by TylerBarnes** [comment]
I'm also getting a 500 error but I think it's for a different reason.

I'm on WPGQL v0.6.1

```
There has been a critical error on your website.

Learn more about debugging in WordPress.

Fatal error: Uncaught Error: Call to undefined method WPGraphQL\Types::list_of() in /code/wp-content/plugins/wp-graphql-content-blocks-master/src/types/block-type.php:113
Stack trace:
#0 /code/wp-content/plugins/wp-graphql-content-blocks-master/src/data/fields.php(110): WPGraphQL\Extensions\ContentBlocks\Types\BlockType::get_list_type()
#1 /code/wp-includes/class-wp-hook.php(290): WPGraphQL\Extensions\ContentBlocks\Data\Fields->add_fields(Array)
#2 /code/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#3 /code/wp-content/plugins/wp-graphql-0.6.3/src/Type/WPObjectType.php(213): apply_filters('graphql_post_fi...', Array, Object(WPGraphQL\Type\WPObjectType), Object(WPGraphQL\Registry\TypeRegistry))
#4 /code/wp-content/plugins/wp-graphql in /code/wp-content/plugins/wp-graphql-content-blocks-master/src/types/block-type.php on line 113
```

**Comment by asc2030** [comment]
Same here with the above, Types has been deprecated since 0.6.0

This class was used to access Type definitions pre v0.4.0, but is no longer used. See upgrade guide vor v0.4.0 (https://github.com/wp-graphql/wp-graphql/releases/tag/v0.4.0) for information on updating to use non-static TypeRegistry methods to get_type(), etc.

**Comment by muhzulzidan** [comment]
so do we need to install the  v0.4.0 version ?

**Comment by chriszarate** [comment]
This is resolved in the latest version, can be closed. @Bhammy

**Comment by Bhammy** [comment]
> This is resolved in the latest version, can be closed. @Bhammy

Thanks!
