### ISSUE TITLE
Blocks dont show up in Post or any other GraphQL Query

### ISSUE THREAD

**Issue by maximilianschmidt** [Quartz/wp-graphql-content-blocks#9]
Using **WPGraphql v0.13.3** and **wp-graphql-content-blocks v0.7.0** the `blocks` field doesn't show up in the Query for Posts (or any other Custom Post Type). 

The following sample query

```
{
  postBy(id: "cG9zdDoxOA==") {
    title
    blocks {
      type
    }
  }
}
```

will throw 

```
{
  "errors": [
    {
      "message": "Cannot query field \"blocks\" on type \"Post\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
  ]
}
```

Am i missing something or are more recent versions of WPGraphQL breaking this Plugin? Whats the latest tested WPGraphQL Version for this Plugin?

**Comment by r1987** [comment]
Notice the same case.

**Comment by emaildano** [comment]
@TylerBarnes @jasonbahl are you aware of any breaking changes in WPGraphQL that would affected this?

**Comment by chriszarate** [comment]
This is resolved in the latest release, can be closed. @Bhammy
